"""
AgriVault – Clean Lending Club Loan Data as Agri-Credit Risk Proxy (Silver Layer)
==================================================================================
The Lending Club dataset (loan.csv from kaggle) is used as a structural proxy
for agricultural credit risk. We extract financial-risk features that are
analogous to what a Kisan Credit Card / FPO lender would see:

    loan grade → credit risk tier
    loan amount → loan size
    interest rate → cost of capital
    loan status → default / performing
    DTI → debt burden
    annual income → borrower capacity
    term → loan tenor

This is explicitly labeled as a proxy dataset in code and output metadata.
The cleaned output is a cross-sectional risk feature table (not time-series).

Input  : data/raw/loans/loan.csv  (from Kaggle: wendykan/lending-club-loan-data)
Output : s3://agrivault-lake-pawan/standardized/loans/loans_risk_features.parquet
         data/standardized/loans/loans_risk_features.parquet (local copy)

Run
---
    python -m src.standardization.clean_loans
"""

from __future__ import annotations

import io
import logging
from pathlib import Path

import boto3
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import yaml

log = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = PROJECT_ROOT / "configs" / "aws_config.yaml"
RAW_LOANS_DIR = PROJECT_ROOT / "data" / "raw" / "loans"
STD_OUT = PROJECT_ROOT / "data" / "standardized" / "loans"


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def make_s3(cfg: dict):
    session = boto3.Session(
        profile_name=cfg["aws"].get("profile"),
        region_name=cfg["aws"].get("region", "ap-south-1"),
    )
    return session.client("s3"), cfg["s3"]["bucket"]


def bucket_key(cfg: dict, layer: str, path: str) -> str:
    prefix = cfg["s3"]["prefixes"].get(layer, f"{layer}/").rstrip("/")
    return f"{prefix}/{path}"


# ---------------------------------------------------------------------------
# Column selection + renaming for Lending Club → AgriVault risk proxy
# ---------------------------------------------------------------------------
LC_COLUMNS = {
    "loan_amnt":         "loan_amount_usd",
    "term":              "term_months_str",
    "int_rate":          "interest_rate_pct_str",
    "grade":             "credit_grade",
    "sub_grade":         "credit_sub_grade",
    "emp_length":        "employment_length",
    "annual_inc":        "annual_income_usd",
    "loan_status":       "loan_status",
    "dti":               "debt_to_income",
    "delinq_2yrs":       "delinquencies_2yr",
    "open_acc":          "open_credit_lines",
    "pub_rec":           "public_records",
    "revol_util":        "revolving_util_str",
    "total_acc":         "total_credit_lines",
    "purpose":           "loan_purpose",
    "addr_state":        "borrower_state",
}

# Loan statuses considered defaults
DEFAULT_STATUSES = {
    "Charged Off",
    "Default",
    "Late (31-120 days)",
    "Does not meet the credit policy. Status:Charged Off",
}


def is_synthetic_proxy(df_header: pd.DataFrame) -> bool:
    """Detect if the CSV is our synthetic KCC proxy (not real Lending Club)."""
    synthetic_cols = {"loan_id", "commodity_category", "season",
                      "disburse_date", "loan_amount_inr", "credit_grade", "ltv_ratio"}
    return bool(synthetic_cols.issubset(set(df_header.columns)))


def clean_loans_proxy(path: Path) -> pd.DataFrame:
    """
    Clean the synthetic KCC loan proxy CSV (generated by generate_loan_proxy.py).
    """
    log.info("Detected synthetic KCC proxy CSV — using proxy cleaner")
    df = pd.read_csv(path)

    df["disburse_date"] = pd.to_datetime(df["disburse_date"], errors="coerce")
    df["loan_amount_inr"] = pd.to_numeric(df["loan_amount_inr"], errors="coerce")
    df["interest_rate_pct"] = pd.to_numeric(df["interest_rate_pct"], errors="coerce")
    df["ltv_ratio"] = pd.to_numeric(df["ltv_ratio"], errors="coerce")
    df["is_default"] = pd.to_numeric(df["is_default"], errors="coerce").astype("Int64")
    df["term_months"] = pd.to_numeric(df["term_months"], errors="coerce").astype("Int64")

    for col in ("state", "commodity_category", "season", "credit_grade"):
        df[col] = df[col].str.strip().str.upper()

    # Grade-level default rates
    grade_stats = (
        df.groupby("credit_grade")["is_default"]
        .agg(["mean", "count"])
        .rename(columns={"mean": "grade_default_rate", "count": "grade_loan_count"})
        .reset_index()
    )
    df = df.merge(grade_stats, on="credit_grade", how="left")

    df = df.drop_duplicates(subset=["loan_id"])
    df = df.reset_index(drop=True)

    log.info("Proxy clean rows: %d | default rate: %.2f%%",
             len(df), df["is_default"].mean() * 100)
    return df


def clean_loans(path: Path) -> pd.DataFrame:
    """
    Load Lending Club CSV, extract risk-proxy features, return clean DataFrame.
    Handles the large file by reading in chunks.
    """
    log.info("Reading Lending Club loans from %s", path)

    available_cols = list(LC_COLUMNS.keys())

    # Peek at column names first
    header_df = pd.read_csv(path, nrows=0)
    actual_cols = [c for c in available_cols if c in header_df.columns]
    missing = set(available_cols) - set(actual_cols)
    if missing:
        log.warning("Missing columns in Lending Club file (may vary by version): %s", missing)

    chunks = []
    chunk_size = 100_000

    for chunk in pd.read_csv(path, usecols=actual_cols, chunksize=chunk_size, low_memory=False):
        chunks.append(chunk)

    df = pd.concat(chunks, ignore_index=True)
    log.info("Loaded %d rows", len(df))

    # ── Rename ────────────────────────────────────────────────────────────
    rename_actual = {k: v for k, v in LC_COLUMNS.items() if k in df.columns}
    df = df.rename(columns=rename_actual)

    # ── Parse interest rate (string "10.5%" → float 10.5) ────────────────
    if "interest_rate_pct_str" in df.columns:
        df["interest_rate_pct"] = (
            df["interest_rate_pct_str"].str.replace("%", "", regex=False)
            .pipe(pd.to_numeric, errors="coerce")
        )
        df = df.drop(columns=["interest_rate_pct_str"])

    # ── Parse revolving utilisation ───────────────────────────────────────
    if "revolving_util_str" in df.columns:
        df["revolving_util_pct"] = (
            df["revolving_util_str"].str.replace("%", "", regex=False)
            .pipe(pd.to_numeric, errors="coerce")
        )
        df = df.drop(columns=["revolving_util_str"])

    # ── Parse term months (string "36 months" → int 36) ──────────────────
    if "term_months_str" in df.columns:
        df["term_months"] = (
            df["term_months_str"].str.extract(r"(\d+)")[0]
            .pipe(pd.to_numeric, errors="coerce")
            .astype("Int64")
        )
        df = df.drop(columns=["term_months_str"])

    # ── Binary default flag ───────────────────────────────────────────────
    if "loan_status" in df.columns:
        df["is_default"] = df["loan_status"].isin(DEFAULT_STATUSES).astype(int)

    # ── Cast numeric columns ──────────────────────────────────────────────
    for col in ("loan_amount_usd", "annual_income_usd", "debt_to_income",
                "delinquencies_2yr", "open_credit_lines", "public_records",
                "total_credit_lines"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # ── Normalise text ────────────────────────────────────────────────────
    for col in ("credit_grade", "credit_sub_grade", "loan_purpose",
                "borrower_state", "loan_status"):
        if col in df.columns:
            df[col] = df[col].str.strip().str.upper()

    # ── Filter: keep only Fully Paid, Charged Off (clear ground truth) ────
    # and the late/default statuses — removes "Current" (in-flight, no outcome)
    clear_statuses = {
        "FULLY PAID",
        "CHARGED OFF",
        "DEFAULT",
        "LATE (31-120 DAYS)",
        "LATE (16-30 DAYS)",
        "DOES NOT MEET THE CREDIT POLICY. STATUS:CHARGED OFF",
        "DOES NOT MEET THE CREDIT POLICY. STATUS:FULLY PAID",
    }
    if "loan_status" in df.columns:
        df = df[df["loan_status"].isin(clear_statuses)]

    # ── Compute default rate per grade (used as mandi-level risk proxy) ───
    if "credit_grade" in df.columns and "is_default" in df.columns:
        grade_stats = (
            df.groupby("credit_grade")["is_default"]
            .agg(["mean", "count"])
            .rename(columns={"mean": "grade_default_rate", "count": "grade_loan_count"})
            .reset_index()
        )
        df = df.merge(grade_stats, on="credit_grade", how="left")

    # ── Add proxy metadata ────────────────────────────────────────────────
    df["data_source"] = "lending_club_proxy"
    df["proxy_note"] = (
        "Lending Club consumer loan data used as structural proxy for "
        "agricultural credit risk. Not actual Kisan Credit Card data."
    )

    # ── Deduplicate ────────────────────────────────────────────────────────
    df = df.drop_duplicates()
    df = df.reset_index(drop=True)

    log.info("Clean loan rows: %d | default rate: %.1f%%",
             len(df),
             df["is_default"].mean() * 100 if "is_default" in df.columns else float("nan"))

    return df


def write_parquet_to_s3(df: pd.DataFrame, s3, bucket: str, key: str) -> None:
    table = pa.Table.from_pandas(df, preserve_index=False)
    buf = io.BytesIO()
    pq.write_table(table, buf, compression="snappy")
    buf.seek(0)
    s3.put_object(Bucket=bucket, Key=key, Body=buf.getvalue())
    log.info("Written → s3://%s/%s", bucket, key)


def find_loan_csv(raw_dir: Path) -> Path:
    """Find the Lending Club CSV — filename varies by download method."""
    candidates = list(raw_dir.glob("*.csv")) + list(raw_dir.glob("loan/*.csv"))
    if not candidates:
        raise FileNotFoundError(
            f"No CSV found in {raw_dir}. "
            "Run: kaggle datasets download -d wendykan/lending-club-loan-data "
            f"-p {raw_dir} --unzip"
        )
    # Prefer the largest file if multiple CSVs
    return max(candidates, key=lambda p: p.stat().st_size)


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
    )

    cfg = load_config()
    s3, bucket = make_s3(cfg)

    loan_csv = find_loan_csv(RAW_LOANS_DIR)
    log.info("Using loan file: %s", loan_csv)

    header = pd.read_csv(loan_csv, nrows=0)
    if is_synthetic_proxy(header):
        df = clean_loans_proxy(loan_csv)
    else:
        df = clean_loans(loan_csv)

    # Write to S3
    s3_key = bucket_key(cfg, "standardized", "loans/loans_risk_features.parquet")
    write_parquet_to_s3(df, s3, bucket, s3_key)

    # Write locally
    STD_OUT.mkdir(parents=True, exist_ok=True)
    local_out = STD_OUT / "loans_risk_features.parquet"
    df.to_parquet(local_out, index=False)
    log.info("Local copy: %s", local_out)

    log.info("✓ Loans standardized and written to S3")


if __name__ == "__main__":
    main()
